# Site Settings
title: LayoutSchool.com
email: contact@layoutschool.com
description: > # this means to ignore newlines until "baseurl:"
  LayoutSchool.com, a resource to get started with front-end development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://layoutschool.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll


# Build settings
markdown: kramdown
permalink: /:categories/:title
highlighter: rouge

#Site Details
license: ""
license-url: ""
author: "LayoutSchool"

# Jekyll Redirect From Plugin for Redirects from redirect_from in template-overviews/blog-with-sidebar
gems:
  - jekyll-redirect-from

# Pagination
paginate: 3

# Compile to css from this folder, :nested, :compact, :expanded, :compressed
sass:
  sass_dir: scss
  style: :nested